function [v]=generate_random(V,U,tol)

%function that receive two matrices and gives back
%a vector orthogonal to the space generated by columns 
%of both matrices.

%initializations
find=0;
k=0;
mat=[V,U];
[i,j]=size(mat);

%repeat one step of Gram–Schmidt orthogonalization until
%a vector orthogonal to all columns is found
while (find==0)&&(k<100)
    k=k+1;
    %vectors initially choosen random and then orthogonalized
    w=rand(i,1);
    r=mat'*w;
    projection=r'.*mat;
    for s=1:size(projection,2)
        w=w-projection(:,s);
    end
    if (norm(w)>tol)
        find=1;
        w;
        v=w/norm(w);
    end
end

%error print if the orthogonal vector isn't found
if k==100 
    fprintf('error, v not found. \n');
end

end
